# Generated by Django 4.2.7 on 2024-01-08 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
